#############################################################################
# Makefile for building: digits_ios.app/Contents/MacOS/digits_ios
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ../digits_ios/digits_ios.pro
# Template: app
# Command: /Users/apple/Qt5.7.0/5.7/ios/bin/qmake -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -spec macx-xcode -o digits_ios.xcodeproj/project.pbxproj ../digits_ios/digits_ios.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/apple/Qt5.7.0/5.7/ios/bin/qmake
digits_ios.xcodeproj/project.pbxproj: ../digits_ios/digits_ios.pro ../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/qmake.conf ../../../Qt5.7.0/5.7/ios/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/qdevice.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/device_config.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/unix.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/mac.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/ios.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/sanitize.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/clang.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/clang-mac.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/ios/clang.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/common/ios/qmake.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/qconfig.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_iosgamepad.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qdds.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/qt_config.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/qt_config.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-xcode/qmake.conf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/default_pre.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/default_pre.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/resolve_config.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/default_post.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/sdk.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/sdk.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/default_post.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/qml_debug.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/warn_on.prf \
		../../../Qt5.7.0/5.7/ios/plugins/platforms/libqios_debug.prl \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/qt.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/qt.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/resources.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/moc.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/unix/opengl.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/uic.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/unix/thread.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/file_copies.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/rez.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/testcase_targets.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/exceptions.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/yacc.prf \
		../../../Qt5.7.0/5.7/ios/mkspecs/features/lex.prf \
		../digits_ios/digits_ios.pro \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../digits_ios/resources.qrc \
		../../../Qt5.7.0/5.7/ios/lib/libQt5PlatformSupport_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5DBus_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libqtfreetype_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5Gui_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libqtharfbuzzng_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5Core_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libqtpcre_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5MultimediaWidgets_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5Widgets_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5Multimedia_debug.prl \
		../../../Qt5.7.0/5.7/ios/lib/libQt5Network_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/mediaservice/libqavfcamera_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/mediaservice/libqavfmediaplayer_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/mediaservice/libqtmedia_audioengine_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/audio/libqtaudio_coreaudio_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/playlistformats/libqtmultimedia_m3u_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqdds_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqicns_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqico_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqmacjp2_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqtga_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqtiff_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqwbmp_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqwebp_debug.prl \
		../../../Qt5.7.0/5.7/ios/plugins/bearer/libqgenericbearer_debug.prl
	$(QMAKE) -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -spec macx-xcode -o digits_ios.xcodeproj/project.pbxproj ../digits_ios/digits_ios.pro
../../../Qt5.7.0/5.7/ios/mkspecs/features/spec_pre.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/qdevice.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/features/device_config.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/unix.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/mac.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/ios.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/sanitize.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/gcc-base.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/clang.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/clang-mac.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/ios/clang.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/common/ios/qmake.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/qconfig.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_iosgamepad.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qdds.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qicns.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qico.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qios.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../../../Qt5.7.0/5.7/ios/mkspecs/features/qt_functions.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/qt_config.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/qt_config.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/qmake.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-xcode/qmake.conf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.7.0/5.7/ios/mkspecs/features/exclusive_builds.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/default_pre.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/default_pre.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/default_pre.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/resolve_config.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/resolve_config.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/default_post.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/sdk.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/sdk.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/default_post.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/objective_c.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/qml_debug.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/warn_on.prf:
../../../Qt5.7.0/5.7/ios/plugins/platforms/libqios_debug.prl:
../../../Qt5.7.0/5.7/ios/mkspecs/features/qt.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/qt.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/resources.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/moc.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/unix/opengl.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/uic.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/unix/thread.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/file_copies.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/mac/rez.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/testcase_targets.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/features/testcase_targets.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/exceptions.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/yacc.prf:
../../../Qt5.7.0/5.7/ios/mkspecs/features/lex.prf:
../digits_ios/digits_ios.pro:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
../../../Qt5.7.0/5.7/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../digits_ios/resources.qrc:
../../../Qt5.7.0/5.7/ios/lib/libQt5PlatformSupport_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5DBus_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libqtfreetype_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5Gui_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libqtharfbuzzng_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5Core_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libqtpcre_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5MultimediaWidgets_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5Widgets_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5Multimedia_debug.prl:
../../../Qt5.7.0/5.7/ios/lib/libQt5Network_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/mediaservice/libqavfcamera_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/mediaservice/libqavfmediaplayer_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/mediaservice/libqtmedia_audioengine_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/audio/libqtaudio_coreaudio_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/playlistformats/libqtmultimedia_m3u_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqdds_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqicns_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqico_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqmacjp2_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqtga_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqtiff_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqwbmp_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/imageformats/libqwebp_debug.prl:
../../../Qt5.7.0/5.7/ios/plugins/bearer/libqgenericbearer_debug.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -spec macx-xcode -o digits_ios.xcodeproj/project.pbxproj ../digits_ios/digits_ios.pro

qmake_all: FORCE

